language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
branches:
  only:
  - master

env:
  - PYTHONPATH=.
install: 
  - pip install tox

script: 
  - tox

notifications:
  email:
    recipients:
      - locvx1234@gmail.com
    on_success: change
    on_failure: always
